version: '3.8'
services:
   web:
       build: .
       command: >
           sh -c "python manage.py migrate &&
                  python manage.py collectstatic --noinput &&
                  gunicorn phonelist.wsgi:application -b 0.0.0.0:8000"
       ports:
         - 8000:8000
       volumes:
        - ./certs/localhost.crt:/app/localhost.crt
        - ./certs/device.key:/app/device.key
   nginx:
       image: nginx:latest
       ports:
         - "80:80"
         - "443:443"
       volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf
         - ./certs/localhost.crt:/etc/nginx/localhost.crt
         - ./certs/device.key:/etc/nginx/device.key
       depends_on:
         - web