# Generated by Django 5.0.1 on 2024-01-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_phone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='phone1',
            new_name='Phone1',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='phone2',
            new_name='Phone2',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='phone3',
            new_name='Phone3',
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='photo',
            new_name='default_photo',
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
